-- MySQL Script generated by MySQL Workbench
-- Sun May 23 19:43:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locations` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `locationscol_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`routes` (
  `id` INT NOT NULL,
  `from_id` INT NOT NULL,
  `to_id` INT NOT NULL,
  `cost` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_routes_locations_idx` (`from_id` ASC) VISIBLE,
  INDEX `fk_routes_locations1_idx` (`to_id` ASC) VISIBLE,
  CONSTRAINT `fk_routes_locations`
    FOREIGN KEY (`from_id`)
    REFERENCES `mydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_routes_locations1`
    FOREIGN KEY (`to_id`)
    REFERENCES `mydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`problems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`problems` (
  `id` INT NOT NULL,
  `from_id` INT NOT NULL,
  `to_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_problems_locations1_idx` (`from_id` ASC) VISIBLE,
  INDEX `fk_problems_locations2_idx` (`to_id` ASC) VISIBLE,
  CONSTRAINT `fk_problems_locations1`
    FOREIGN KEY (`from_id`)
    REFERENCES `mydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_problems_locations2`
    FOREIGN KEY (`to_id`)
    REFERENCES `mydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solutions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solutions` (
  `problem_id` INT NOT NULL,
  `cost` INT NULL,
  PRIMARY KEY (`problem_id`),
  INDEX `fk_solutions_problems1_idx` (`problem_id` ASC) VISIBLE,
  CONSTRAINT `fk_solutions_problems1`
    FOREIGN KEY (`problem_id`)
    REFERENCES `mydb`.`problems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
